In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import fpgrowth

In [4]:
import pandas as pd
import numpy as np
import os

file_path = '/content/drive/My Drive/WebM_csproject/dataset'
files = os.listdir(file_path)
print(files)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


['users_fr.csv', 'items_en.csv', 'explicit_ratings_fr.csv', 'implicit_ratings_fr.csv', 'users_en.csv', 'implicit_ratings_en.csv', 'items_fr.csv', 'explicit_ratings_en.csv']


#**English dataset**

In [5]:
df_exprate_en = pd.read_csv(file_path + '/'+ 'explicit_ratings_en.csv')
df_users_en = pd.read_csv(file_path + '/'+ 'users_en.csv')
df_imprate_en = pd.read_csv(file_path + '/'+ 'implicit_ratings_en.csv')
df_items_en = pd.read_csv(file_path + '/'+ 'items_en.csv')

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [ ]:
df_users_en

In [ ]:
df_imprate_en

In [22]:
df_exprate_en

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


user_id  item_id  watch_percentage        created_at  rating
0      224557      510               100   9/28/2018 16:18      10
1      224293      510               100   9/28/2018 17:20      10
2      224442      510               100   10/1/2018 20:11      10
3      196845      510                 7   10/6/2018 13:12       1
4      265845      510               100  10/10/2018 21:17      10
...       ...      ...               ...               ...     ...
3654   184438   403215               100    9/11/2021 3:01      10
3655   184438   403216               100   9/12/2021 15:16      10
3656   603725   403216                53    7/12/2021 8:36       6
3657   184438   403217               100    9/13/2021 2:57      10
3658   184438   403218               100    9/13/2021 3:16      10

[3659 rows x 5 columns]

In [21]:
df_items_en

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


item_id language                                               name  \
0         510       en                     What is OneDrive for Business?   
1         511       en         Add, restore, delete documents on OneDrive   
2         512       en                                    Share documents   
3         513       en                                        Recycle bin   
4         514       en  Sync OneDrive for Business to your computer (W...   
...       ...      ...                                                ...   
1162   422593       en                               Create custom fields   
1163   422594       en                      Make a reservation [Customer]   
1164   422595       en                         Make a reservation [Staff]   
1165   422596       en                         Manage your availabilities   
1166   422597       en                      Integrate Bookings into TEAMS   

      nb_views                                        description  created_at  \
0       1114.0  OneDrive for Businessis an online libraryto st...        2016   
1        547.0  To create a new document in OneDriveclick New,...        2016   
2        607.0  By default, all content is private, so you don...        2016   
3        278.0  When you delete a file or afolder, OneDrive gi...        2016   
4        312.0  The one drive synchronization application is a...        2016   
...        ...                                                ...         ...   
1162      22.0                                                NaN        2021   
1163      22.0                                                NaN        2021   
1164      19.0                                                NaN        2021   
1165      19.0                                                NaN        2021   
1166      20.0                                                NaN        2021   

     Difficulty                                                Job  \
0      Beginner                                                 []   
1      Beginner                                                 []   
2      Beginner                                                 []   
3      Beginner  ['Accounting', 'Financial', 'Human resources',...   
4      Beginner                                                 []   
...         ...                                                ...   
1162        NaN                                                 []   
1163        NaN                                                 []   
1164        NaN                                                 []   
1165        NaN                                                 []   
1166        NaN                                                 []   

          Software                             Theme  duration      type  
0     ['OneDrive']                      ['Discover']      42.0  tutorial  
1     ['OneDrive']  ['Share', 'Produce', 'Organize']     122.0  tutorial  
2     ['OneDrive']          ['Share', 'Collaborate']     176.0  tutorial  
3     ['OneDrive']           ['Produce', 'Organize']      46.0  tutorial  
4     ['OneDrive']           ['Produce', 'Organize']     163.0  tutorial  
...            ...                               ...       ...       ...  
1162  ['Bookings']          ['Produce', 'Customize']      81.0  tutorial  
1163  ['Bookings']                       ['Produce']     133.0  tutorial  
1164  ['Bookings']                       ['Produce']     115.0  tutorial  
1165  ['Bookings']                      ['Organize']     102.0  tutorial  
1166  ['Bookings']                       ['Produce']      96.0  tutorial  

[1167 rows x 12 columns]

In [49]:
df_items_en_itemsgenre = df_items_en.loc[:,['item_id','Job','Theme']]
print(df_items_en_itemsgenre.head(10))

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


#bỏ

In [ ]:
def split_and_strip(job_list):
  return [job.strip('') for job in job_list]

df_items_en["Job_split"] = df_items_en["Job"].apply(split_and_strip)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [ ]:
df_items_en["Job_split"]

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


0                                                  [[, ]]
1                                                  [[, ]]
2                                                  [[, ]]
3       [[, ', A, c, c, o, u, n, t, i, n, g, ', ,,  , ...
4                                                  [[, ]]
                              ...                        
1162                                               [[, ]]
1163                                               [[, ]]
1164                                               [[, ]]
1165                                               [[, ]]
1166                                               [[, ]]
Name: Job_split, Length: 1167, dtype: object

#tiếp

In [103]:
df_items_en['Theme'].unique()

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


array(["['Discover']", "['Share', 'Produce', 'Organize']",
       "['Share', 'Collaborate']", "['Produce', 'Organize']",
       "['Produce']", "['Customize']", "['Customize', 'Communicate']",
       "['Research']", "['Organize']", "['Communicate']",
       "['Organize', 'Communicate']", "['Share']", '[]',
       "['Share', 'Collaborate', 'Communicate']",
       "['Produce', 'Collaborate']", "['Share', 'Organize']",
       "['Share', 'Produce']", "['Discover', 'Research']",
       "['Collaborate', 'Customize']", "['Collaborate']",
       "['Discover', 'Organize']", "['Discover', 'Produce']",
       "['Analyze']", "['Produce', 'Customize']",
       "['Produce', 'Research']", "['Collaborate', 'Communicate']",
       "['Share', 'Organize', 'Collaborate']", "['Organize', 'Analyze']",
       "['Share', 'Communicate']", "['Organize', 'Collaborate']",
       "['Discover', 'Collaborate']", "['Produce', 'Analyze']",
       "['Mobility']", "['Discover', 'Collaborate', 'Communicate']",
       "['D

In [ ]:
df_items_en['Job'].unique()

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


array(['[]',
       "['Accounting', 'Financial', 'Human resources', 'Project manager', 'Project management', 'Assistant', 'Communication', 'Marketing']",
       "['Accounting', 'Financial', 'Human resources', 'Project manager', 'Assistant', 'Communication', 'Marketing']",
       "['Accounting', 'Project manager', 'Project management', 'Assistant', 'Communication', 'Marketing']",
       "['Accounting', 'Financial', 'Human resources', 'Project manager', 'Communication', 'Marketing']",
       "['Accounting', 'Human resources', 'Project manager', 'Project management', 'Assistant', 'Communication', 'Marketing']",
       "['Accounting', 'Financial', 'Human resources', 'Project manager', 'Project management', 'Communication', 'Marketing']",
       "['Accounting', 'Financial', 'Human resources', 'Project management', 'Assistant', 'Communication', 'Marketing']",
       "['Accounting', 'Financial', 'Human resources', 'Project management', 'Communication', 'Marketing']",
       "['Accounting', 'F

In [ ]:
import ast
unique_jobs = df_items_en['Job'].unique()
job_lists = []

for jobs in unique_jobs:
  if jobs == "[]":
    continue
  job = ast.literal_eval(jobs)
  for item in job:
    job_lists.append(item)

In [104]:
unique_themes = df_items_en['Theme'].unique()
theme_lists = []

for themes in unique_themes:
  if themes == "[]":
    continue
  theme = ast.literal_eval(themes)
  for item1 in theme:
    theme_lists.append(item1)

print(theme_lists)

['Discover', 'Share', 'Produce', 'Organize', 'Share', 'Collaborate', 'Produce', 'Organize', 'Produce', 'Customize', 'Customize', 'Communicate', 'Research', 'Organize', 'Communicate', 'Organize', 'Communicate', 'Share', 'Share', 'Collaborate', 'Communicate', 'Produce', 'Collaborate', 'Share', 'Organize', 'Share', 'Produce', 'Discover', 'Research', 'Collaborate', 'Customize', 'Collaborate', 'Discover', 'Organize', 'Discover', 'Produce', 'Analyze', 'Produce', 'Customize', 'Produce', 'Research', 'Collaborate', 'Communicate', 'Share', 'Organize', 'Collaborate', 'Organize', 'Analyze', 'Share', 'Communicate', 'Organize', 'Collaborate', 'Discover', 'Collaborate', 'Produce', 'Analyze', 'Mobility', 'Discover', 'Collaborate', 'Communicate', 'Discover', 'Communicate', 'Research', 'Organize', 'Collaborate', 'Communicate', 'Share', 'Organize', 'Collaborate', 'Communicate', 'Share', 'Organize', 'Collaborate', 'Customize', 'Communicate', 'Organize', 'Customize', 'Collaborate', 'Communicate', 'Research

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [44]:
def unique_values(input_list):
    unique_list = []
    for item in input_list:
        if item not in unique_list:
            unique_list.append(item)
    return unique_list

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [47]:
unique_job_lists = unique_values(job_lists)
print(unique_job_lists)

['Accounting', 'Financial', 'Human resources', 'Project manager', 'Project management', 'Assistant', 'Communication', 'Marketing', 'Salesman', 'Manager']


/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [105]:
unique_theme_lists = unique_values(theme_lists)
print(unique_theme_lists)

['Discover', 'Share', 'Produce', 'Organize', 'Collaborate', 'Customize', 'Communicate', 'Research', 'Analyze', 'Mobility', 'Telephony & Visio', 'New features', 'Other Products', 'Accessibility', 'Security']


/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


# Ẩn

In [ ]:
temp = []
for index, row in df_items_en.iterrows():
  row['Job'] = ast.literal_eval(row['Job'])
  for jobs in row['Job']:
    if jobs != "[]":
      temp.append([jobs])
  row['Job'] = temp
  print(row['Job'])
  temp.clear()


#tiếp

In [106]:
unique_values1 = [job for job in unique_job_lists]
unique_values2 = [theme for theme in unique_theme_lists]

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [57]:
df_items_en['Job']

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


0                                                      []
1                                                      []
2                                                      []
3       ['Accounting', 'Financial', 'Human resources',...
4                                                      []
                              ...                        
1162                                                   []
1163                                                   []
1164                                                   []
1165                                                   []
1166                                                   []
Name: Job, Length: 1167, dtype: object

# methods of bring out the occurence matrix (hide)

In [65]:
print (unique_values1)
job_matrix = np.zeros((len(df_items_en_itemsgenre), len(unique_values1)))
for i in range(len(df_items_en_itemsgenre)):
  for j in range(len(unique_values1)):
    if df_items_en_itemsgenre.loc[i, 'Job'][0] == unique_values1[j]:
          job_matrix[i, j] += 1
print(job_matrix)

df_itemforfp = pd.DataFrame(job_matrix, columns = unique_values1)
df_enitemforfp = df_itemforfp.astype("int")

['Accounting', 'Financial', 'Human resources', 'Project manager', 'Project management', 'Assistant', 'Communication', 'Marketing', 'Salesman', 'Manager']
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


#FP-Growth tree

In [108]:
def count_occurrences_job(job_list):
    return {value: job_list.count(value) for value in unique_values1}

def count_occurrences_theme(theme_list):
    return {value: theme_list.count(value) for value in unique_values2}

resultjob_df = df_items_en_itemsgenre['Job'].apply(count_occurrences_job).apply(pd.Series)
resultjob_df = resultjob_df.fillna(0)
resultjob_df = resultjob_df.astype('bool')

resulttheme_df = df_items_en_itemsgenre['Theme'].apply(count_occurrences_theme).apply(pd.Series)
resulttheme_df = resulttheme_df.fillna(0)
resulttheme_df = resulttheme_df.astype('bool')

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [109]:
resultjob_df

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


Accounting  Financial  Human resources  Project manager  \
0          False      False            False            False   
1          False      False            False            False   
2          False      False            False            False   
3           True       True             True             True   
4          False      False            False            False   
...          ...        ...              ...              ...   
1162       False      False            False            False   
1163       False      False            False            False   
1164       False      False            False            False   
1165       False      False            False            False   
1166       False      False            False            False   

      Project management  Assistant  Communication  Marketing  Salesman  \
0                  False      False          False      False     False   
1                  False      False          False      False     False   
2                  False      False          False      False     False   
3                   True       True           True       True     False   
4                  False      False          False      False     False   
...                  ...        ...            ...        ...       ...   
1162               False      False          False      False     False   
1163               False      False          False      False     False   
1164               False      False          False      False     False   
1165               False      False          False      False     False   
1166               False      False          False      False     False   

      Manager  
0       False  
1       False  
2       False  
3       False  
4       False  
...       ...  
1162    False  
1163    False  
1164    False  
1165    False  
1166    False  

[1167 rows x 10 columns]

In [119]:
fpgrowth(resultjob_df, min_support=1/1167, use_colnames=True)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


support                                           itemsets
0    0.186804                                        (Marketing)
1    0.130249                                    (Communication)
2    0.127678                                        (Financial)
3    0.089974                                  (Project manager)
4    0.088260                               (Project management)
..        ...                                                ...
260  0.000857                         (Manager, Project manager)
261  0.000857           (Assistant, Project management, Manager)
262  0.000857              (Assistant, Manager, Project manager)
263  0.000857     (Project management, Manager, Project manager)
264  0.000857  (Assistant, Project management, Manager, Proje...

[265 rows x 2 columns]

In [110]:
resulttheme_df

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


Discover  Share  Produce  Organize  Collaborate  Customize  Communicate  \
0         True  False    False     False        False      False        False   
1        False   True     True      True        False      False        False   
2        False   True    False     False         True      False        False   
3        False  False     True      True        False      False        False   
4        False  False     True      True        False      False        False   
...        ...    ...      ...       ...          ...        ...          ...   
1162     False  False     True     False        False       True        False   
1163     False  False     True     False        False      False        False   
1164     False  False     True     False        False      False        False   
1165     False  False    False      True        False      False        False   
1166     False  False     True     False        False      False        False   

      Research  Analyze  Mobility  Telephony & Visio  New features  \
0        False    False     False              False         False   
1        False    False     False              False         False   
2        False    False     False              False         False   
3        False    False     False              False         False   
4        False    False     False              False         False   
...        ...      ...       ...                ...           ...   
1162     False    False     False              False         False   
1163     False    False     False              False         False   
1164     False    False     False              False         False   
1165     False    False     False              False         False   
1166     False    False     False              False         False   

      Other Products  Accessibility  Security  
0              False          False     False  
1              False          False     False  
2              False          False     False  
3              False          False     False  
4              False          False     False  
...              ...            ...       ...  
1162           False          False     False  
1163           False          False     False  
1164           False          False     False  
1165           False          False     False  
1166           False          False     False  

[1167 rows x 15 columns]

In [118]:
fpgrowth(resulttheme_df, min_support=1/1167, use_colnames=True)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


support                                   itemsets
0   0.077978                                 (Discover)
1   0.203085                                  (Produce)
2   0.099400                                 (Organize)
3   0.053985                                    (Share)
4   0.070266                              (Collaborate)
..       ...                                        ...
79  0.001714  (Accessibility, Other Products, Mobility)
80  0.001714                  (Accessibility, Mobility)
81  0.000857                 (Accessibility, Customize)
82  0.009426                    (Security, Collaborate)
83  0.000857                       (Organize, Security)

[84 rows x 2 columns]

# ***just used in case of join in databases*** (connect the job of users and the job which items mapping to)

In [ ]:
#check individuality of the users in needy case
dropduplicated_df = df_users_en["user_id"].duplicated(keep='first')
print(dropduplicated_df.nunique())
print(dropduplicated_df.unique())
df_u_en = df_users_en
#grouped_df = df_users_en.groupby("user_id")
#grouped_df["job"] = grouped_df["job"].agg(lambda x: ','.join(str(x)))

1
[False]


/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [ ]:
df_users_en

In [ ]:
#method1 to get frequencies
categorical_columns = ["job"]
df_users_en_job = pd.get_dummies(df_users_en, columns=categorical_columns)
print(df_users_en_job)

In [ ]:
#trong trường hợp biến tất cả row trở thành onehot_encoded các job
#bỏ
dataset = []
for row in df_users_en.iterrows():
  dataset.append(row[1].tolist())

te = TransactionEncoder()
te_ary = te.fit(dataset).transform(dataset)
df_ujob_en1 = pd.DataFrame(te_ary, columns=te.columns_)
df_ujob_en1

In [ ]:
#method2 to get frequencies
unique_values = df_users_en['job'].unique().tolist()

job_matrix = np.zeros((len(df_users_en), len(unique_values)))
for i in range(len(df_users_en)):
    for j in range(len(unique_values)):
        if df_users_en.loc[i, 'job'] == unique_values[j]:
            job_matrix[i, j] = 1

print(job_matrix)
df_forfp = pd.DataFrame(job_matrix, columns = unique_values)
df_enjobforfp = df_forfp.astype("int")

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]


In [ ]:
 df_enjobforfp

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


NameError: ignored

In [ ]:
fpgrowth(df_enjobforfp, min_support=0.6, use_colnames=True)

#**French dataset**

In [ ]:
df_exprate_fr = pd.read_csv(file_path + '/'+ 'explicit_ratings_fr.csv')
df_imprate_fr = pd.read_csv(file_path + '/'+ 'implicit_ratings_en.csv')

In [ ]:
df_users_fr = pd.read_csv(file_path + '/'+ 'users_fr.csv')

In [ ]:
df_items_fr = pd.read_csv(file_path + '/'+ 'items_fr.csv')

In [ ]:
df_items_fr

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


item_id language                                               name  \
0           1       fr  Communiquer : qui peut m'aider ? Qui est dispo...   
1           2       fr  Partager : mises à jour régulières, qui peut f...   
2           3       fr  Collaborer : je finis la 1ère partie, je te la...   
3           4       fr  Chercher : quelles sont les dernières publicat...   
4           5       fr      Produire : finalisez vos documents à distance   
...       ...      ...                                                ...   
1446   420073       fr                       Intégrer Bookings dans Teams   
1447   426111       fr                     La retranscription automatique   
1448   426112       fr                     Mettre en avant un participant   
1449   426113       fr            Enregistrer automatiquement une réunion   
1450   426114       fr                                 Modes présentateur   

      nb_views                                        description  created_at  \
0       1039.0  Bonjour et bienvenue sur cette présentation do...        2016   
1        558.0  Bonjour bienvenue à sous Windows Vista je nous...        2016   
2        703.0  Voila Bonjour à tous je me présente réellement...        2016   
3        248.0  Bonjour à toutes et à tous euh merci de cette ...        2016   
4        445.0  Bonjour bienvenue sur cette plantation codina ...        2016   
...        ...                                                ...         ...   
1446      41.0                                                NaN        2021   
1447       4.0                                                NaN        2021   
1448       3.0                                                NaN        2021   
1449       3.0                                                NaN        2021   
1450      14.0                                                NaN        2021   

     Difficulty Job             Software                        Theme  \
0      Beginner  []                   []                           []   
1           NaN  []                   []                           []   
2      Beginner  []                   []                           []   
3      Beginner  []                   []                           []   
4      Beginner  []                   []                           []   
...         ...  ..                  ...                          ...   
1446        NaN  []         ['Bookings']                 ['Produire']   
1447        NaN  []  ['Microsoft Teams']  ['Collaborer', 'Nouveauté']   
1448        NaN  []  ['Microsoft Teams']  ['Collaborer', 'Nouveauté']   
1449        NaN  []  ['Microsoft Teams']  ['Collaborer', 'Nouveauté']   
1450        NaN  []  ['Microsoft Teams']  ['Collaborer', 'Nouveauté']   

      duration      type  
0       1980.0   webcast  
1       1757.0   webcast  
2       2231.0   webcast  
3       1925.0   webcast  
4       1476.0   webcast  
...        ...       ...  
1446     103.0  tutorial  
1447      89.0  tutorial  
1448      72.0  tutorial  
1449      61.0  tutorial  
1450     117.0  tutorial  

[1451 rows x 12 columns]